name: Lighthouse Check

on:
  push:
    branches:
      - main
  merge_group:
  pull_request:
    branches:
      - main

  workflow_dispatch:

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 18

jobs:
  build:
    name: Run Lighthouse
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm i

      - name: Build docs site
        working-directory: ./
        run: pnpm build
        env:
          NO_GRADIENTS: true

      - name: Run Lighthouse on dist dir
        uses: treosh/lighthouse-ci-action@v10
        with:
          # budgetPath: './.github/workflows/lighthouse-budget.json'
          configPath: './.github/workflows/lighthouserc.json'
